# -*- eval: (index/org-hugo-auto-export-mode 1); -*-
#+AUTHOR: Finn Sauer
#+EMAIL: public@finnsauer.com
#+HUGO_SECTION: blog
#+HUGO_BASE_DIR: ~/web
#+TODO: TODO REVIEW | DONE
#+STARTUP: logdone

* Home Page
:PROPERTIES:
:CUSTOM_ID: h:1648b91c-270b-4ae0-83cc-a6ea90b2d24b
:EXPORT_HUGO_SECTION: /
:EXPORT_FILE_NAME: _index
:END:

#+HTML: <h2>
Under Construction
#+HTML: </h2>

This site currently is under construction; everything you see might
change completely.  It's in its pre-alpha stage, so it's highly
experimental.

For instance the dark mode version isn't working properly, as I, myself,
spend more time in light mode and thus I mostly focus on their
respective colors.  I wish to fix it though.

* About
:PROPERTIES:
:CUSTOM_ID: h:aa4ab31e-3546-4e1a-b1ff-49b7c0dc081b
:EXPORT_HUGO_SECTION: /
:EXPORT_FILE_NAME: about
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :weight 100
:END:

{{< partial "website-git-last-log" >}}

+ Hugo Version: *src_elisp{
   (->> "hugo version"
        shell-command-to-string
        (s-split " ")
        (nth 1))}*
+ Repository Size: *src_elisp{
   (file-size-human-readable
    (apply
     #'+
     (mapcar (lambda (file)
               (file-attribute-size
                (file-attributes
                 (expand-file-name file))))
             (flatten-tree
              (mapcar (lambda (file)
                        (unless (s-match "\\.git/" file)
                          file))
                      (directory-files-recursively "~/web" "."))))))}*
+ Website Size: *src_elisp{
   (file-size-human-readable
    (apply
     #'+
     (mapcar (lambda (file)
              (file-attribute-size
               (file-attributes
                (expand-file-name file))))
             (directory-files-recursively "~/web/public" "."))))}*
+ Website's LOC (HTML and SCSS): *src_elisp{
   (->> (directory-files-recursively (expand-file-name "~/web") "\\(html\\|scss\\)$")
        (--map (unless (or (s-match "public/" it) (s-match ".git/" it))
                 it))
        flatten-tree
        (--map (with-temp-buffer
                 (insert-file-contents it)
                 (count-lines (point-min) (point-max))))
        (apply #'+))}*

This website is crafted with [[https://gohugo.io/][Hugo]] and Emacs' [[https://orgmode.org/][Org Mode]]: [[https://ox-hugo.scripter.co/][ox-hugo]].  The
underlying HTML and CSS (SCSS[fn:1:I am not referencing their website
because of political reasons.]) is written by me.  Each content-- that
is the text of a site-- is written in a [[https://gitlab.com/indexfinn/website/-/blob/master/website.org][single Org Mode file]].

The sever is hosted at [[https://www.vultr.com/?ref=8825891-6G][Vultr]].  One of the cheapest and efficient options
I could find.  They provide you with everything you need: with a static
IPv4/IPv6 address, option to open the port 25 for sending mail, and even
more.  After assigning your domain name to the IP address it is as
simple as =ssh your-domain-name.com=.

The website is under version control via [[http://www.git-scm.com/][Git]]; a link to the repository
can be found [[https://gitlab.com/indexfinn/website/-/commits/master][here]].

* Contact
:PROPERTIES:
:CUSTOM_ID: h:1da94a3e-a886-4769-8634-030029442f78
:EXPORT_HUGO_SECTION: /
:EXPORT_FILE_NAME: contact
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :weight 101
:END:

Questions or thoughts are always appreciated.

+ public@finnsauer.com

[[https://finnsauer.com/public-gpg-key.ascii][This]] is my public [[https://gnupg.org/][GnuPG]] key.  Just import it in order to send encrypted
email to me.

You can import my public GnuPG key with the following command:

#+begin_src
curl -LZ https://finnsauer.com/public-gpg-key.ascii | gpg --import
#+end_src

* Dotemacs
:PROPERTIES:
:CUSTOM_ID: h:30d120cd-d658-4520-a9b4-d78bd0b984bd
:EXPORT_HUGO_SECTION: /dotemacs
:EXPORT_FILE_NAME: _index
:END:

{{< partial "dotemacs-git-last-log" >}}

* Blog
:PROPERTIES:
:CUSTOM_ID: h:c761582c-bf98-473f-92fd-dca9374c819e
:EXPORT_HUGO_SECTION: /blog
:EXPORT_FILE_NAME: _index
:END:

This blog will mostly be about technology and close related topics.  In
the future I might split it into multiple blogs with different topics--
a hierarchically based system-- or a tag based system.

Right now there is a beta version of tags.  That can be found [[https://finnsauer.com/tags/][here]].

* Feeds
:PROPERTIES:
:CUSTOM_ID: h:62b9de36-a1c0-4b94-b25f-5401d710430e
:EXPORT_HUGO_SECTION: /
:EXPORT_FILE_NAME: feeds
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :weight 104
:END:

# TODO: remove the parentheses and add it as a foot note; still need to
# figure things more out

The specific RSS Feed of a tag can be found on their respective sites;
go to [[https://finnsauer.com/tags/][this page]] and select the one you want to subscribe (This is not a
typical subscription as you know it; you simply put the RSS Feed URL
into your RSS Feed reader and be done with it.  If you want to
unsubscribe, remove it.).  A master feed-- that is a feed that embodies
all the tags-- can be found [[https://finnsauer.com/blog/index.xml][here]].

* License
:PROPERTIES:
:CUSTOM_ID: h:5ac6a93c-858b-46c8-b4d8-963973a4d188
:EXPORT_HUGO_SECTION: /
:EXPORT_FILE_NAME: license
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :weight 105
:END:

TODO: more things on copyleft licenses and why you should use them.

+ GNU Public License Version 3.0 or later quick guide:
  + https://www.gnu.org/licenses/quick-guide-gplv3.html
+ Creative Commons BY-SA 4.0 quick guide:
  + https://creativecommons.org/licenses/by-sa/4.0/

* NO-HUGO Dummy Sites
:PROPERTIES:
:CUSTOM_ID: h:6edbcbb3-429f-4db5-8f98-ffae3e5600e9
:END:

** Blog
:PROPERTIES:
:CUSTOM_ID: h:615e67e6-1f88-4dd3-8f9e-74588059d3bd
:EXPORT_HUGO_SECTION: /
:EXPORT_FILE_NAME: dummy-blog
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :url blog/ :weight 103
:END:

** Dotemacs
:PROPERTIES:
:CUSTOM_ID: h:fa744b47-045f-4126-9647-3e6e3f079f1a
:EXPORT_HUGO_SECTION: /
:EXPORT_FILE_NAME: dummy-dotemacs
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :url dotemacs/ :weight 102
:END:

* NO-HUGO Blog Posts
:PROPERTIES:
:CUSTOM_ID: h:b3ace5f9-c588-481d-994d-3871b8bc6f45
:END:

** DONE Hello World                                              :org:emacs:
CLOSED: [2021-02-14 Sun]
:PROPERTIES:
:EXPORT_FILE_NAME: hello-world
:CUSTOM_ID: h:def96466-2080-40df-964e-7259f95e5575
:END:

#+begin_abstract
Some abstract text.  Optio cumque nihil impedit quo minus id quod maxime
placeat  facere  possimus  omnis  voluptas  assumenda  est  omnis  dolor
repellendus Temporibus autem quibusdam et aut officiis debitis aut rerum
necessitatibus  saepe  eveniet  ut  et voluptates  repudiandae  sint  et
molestiae  non recusandae  Itaque  earum rerum  hic  tenetur a  sapiente
delectus ut aut!
#+end_abstract

This is my first blog post; noch eine schöne Zeit!

#+begin_quote
This is a quote.

Over multiple lines!
#+end_quote
