# -*- eval: (index/org-hugo-auto-export-mode 1); -*-
#+AUTHOR: Finn Sauer
#+EMAIL: <public@finnsauer.com>
#+HUGO_SECTION: blog
#+HUGO_BASE_DIR: ~/web
#+TODO: TODO REVIEW | DONE
#+STARTUP: logdone

* Home Page
:PROPERTIES:
:CUSTOM_ID: h:1648b91c-270b-4ae0-83cc-a6ea90b2d24b
:EXPORT_HUGO_SECTION: /
:EXPORT_FILE_NAME: _index
:END:

#+HTML: <h2>
Under Construction
#+HTML: </h2>

This site currently is under construction; everything you see might
change completely.  It's in its pre-alpha stage, so it's highly
experimental.

For instance the dark mode version isn't working properly, as I, myself,
spend more time in light mode and thus I mostly focus on their
respective colors.  I wish to fix it though.

* About
:PROPERTIES:
:CUSTOM_ID: h:aa4ab31e-3546-4e1a-b1ff-49b7c0dc081b
:EXPORT_HUGO_SECTION: /
:EXPORT_FILE_NAME: about
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :weight 100
:END:

{{< partial "website-git-last-log" >}}

+ Hugo Version: *src_elisp{
   (nth 4
    (s-split " "
     (shell-command-to-string
      "hugo version")))}*
+ Repository Size: *src_elisp{
   (file-size-human-readable
    (apply
     #'+
     (mapcar (lambda (file)
               (file-attribute-size
                (file-attributes
                 (expand-file-name file))))
             (flatten-tree
              (mapcar (lambda (file)
                        (unless (s-match "\\.git/" file)
                          file))
                      (directory-files-recursively "~/web" "."))))))}*
+ Website Size: *src_elisp{
   (file-size-human-readable
    (apply
     #'+
     (mapcar (lambda (file)
              (file-attribute-size
               (file-attributes
                (expand-file-name file))))
             (directory-files-recursively "~/web/public" "."))))}*
+ Website's LOC (HTML and SCSS): *src_elisp{
   (->> (directory-files-recursively (expand-file-name "~/web") "\\(html\\|scss\\)$")
        (--map (unless (or (s-match "public/" it) (s-match ".git/" it))
                 it))
        flatten-tree
        (--map (with-temp-buffer
                 (insert-file-contents it)
                 (count-lines (point-min) (point-max))))
        (apply #'+))}*

This website is crafted with [[https://gohugo.io/][Hugo]] and Emacs' [[https://orgmode.org/][Org Mode]]: [[https://ox-hugo.scripter.co/][ox-hugo]].  The
underlying HTML and CSS (SCSS[fn:1:I am not referencing their website
because of political reasons.]) is written by me.  Each content-- that
is the text of a site-- is written in a [[https://gitlab.com/indexfinn/website/-/blob/master/website.org][single Org Mode file]].

The website is under version control via [[http://www.git-scm.com/][Git]]; a link to the repository
can be found [[https://gitlab.com/indexfinn/website/-/commits/master][here]].

* Contact
:PROPERTIES:
:CUSTOM_ID: h:1da94a3e-a886-4769-8634-030029442f78
:EXPORT_HUGO_SECTION: /
:EXPORT_FILE_NAME: contact
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :weight 101
:END:

Questions or thoughts are always appreciated.

+ public@finnsauer.com

The following is my public gpg key.  Just import it in order to send
encrypted email to me.

#+begin_src
-----BEGIN PGP PUBLIC KEY BLOCK-----

mQINBF8xUy4BEADP3oVjbynQw3rkvYyv0ab3aQOw0RyKfybAyDh3SnHCxM04KCPV
SsrLi0t0elyKphcM+Jm/o7js4LQgQrR1oWtBMNm7XBEhjatpRhdqhe8HXXPDWWUo
3fWqf/VkcPk2jmyckXNtSpTDZYpcG1P4HaEV3daBF/Aep4EyfUintlfoPHEjV1RH
i+k+xkJVGxykX07b7wS9C0z89WO7gQu1yu5fkj6VfEQbQhAob5E/UVJ3PYOzdBqZ
MfA7rpE+zKXbY7WrXKSvGlj4tSkNpX6Vpp1psMspYOv48JtMe+amRyr0e0TYc5g7
2XGrMCZQXYeEqmaH1sixYB9DQLTCkU9TaN6C18aoHfOxObHn7oWYu3OivpSavlbY
q6UBrkrdvFR14UMgmh5nSihHbfHC5b24orbCerd+FaQzmg97dt5DmueRzxY+akCZ
KB1gvkT8mmYHAN/1Q5iaEJunt1FDN/CAmGY7DuoiiHeEL+NT8CTfJeM4AJnyd79w
9qGEN9Z7JVekX1PAPjaBdQv6ETpHF/eQW/RX5+33XOVUJb4EnkoDXdD6gl4PhRS/
kJbpU+28Yi0BVgX6LGfZWT1HN/akHWF94nkphvuHegv073M/yAXsy+8ikwB9zOLd
gXDQn4FXyKvajTLQnYoqFYF9mIZljEYnlG39qcRWRz811GoOu0tPG0Ko2QARAQAB
tB9GaW5uIFNhdWVyIDxpbmZvQGZpbm5zYXVlci5jb20+iQJUBBMBCAA+FiEEO7Wm
aGQYJ1zCWYzNhPFAK4c7aygFAmAhtsACGwMFCQHVDl4FCwkIBwIGFQoJCAsCBBYC
AwECHgECF4AACgkQhPFAK4c7ayie2g//YuB9AHuJ0ZE9BPs7BaZ1L0XcpnMZRKwA
ZtoUs1YTSstiHhuc29YFEemW7GRGlWLtTpi8bWTeQ8WUN9h3wqoXxkky9r9dR+Sv
nB1INZEGSgEIdJO+VhbBAFHH26PkRnJG1v3LXG87q1u7y2ttYNj4csm7klq2MYJK
c0awD43o1lun68zbt1/FkMJ/ATY/hmXBd7z3b1+lLslK4FNLzpc2IvmIF0DJsleL
xHu69ULM9DKDSiP8fpDQij7AgU9CAiKoa/blQUhPxzfN8E0oXPBR/u/PK6ShtVof
WyQ0KNuvVFXxAlbkWHSUasqPTad8XfF/xugr2LnH171a0pEv1DdlQiHvbgyaFsva
Cm52G9HTjv5/Re2v0V0h1/0iTju9/FBBQMCHvcbBmffszUO72kKq7zeAZwO+ID6Z
7HTS2sUNdvaiS4Wru/iD+LofT4wKu28E8ILN0BwWNeMI8mIViYsLGExLdEBugtDB
wN+yyGfVMKTlfxAhD8Gx2qKGDcOI4Q7xDfrE89duBfmrThnhd9TyWxAcqgl+0Oje
11X3jm6FysdXfKnC7wAojJ6lTpaXaxzitp4ZmN9Q+VmEVbOaDwk2wiGyARz47b99
flFdOgi92PHLjaDIL+d5Ixgs5JIxdz7iUzPX6uwkJ5Hk/ZB5U7teSeuRg5qOyz1I
jRgm3xFVkza0IUZpbm4gU2F1ZXIgPHB1YmxpY0BmaW5uc2F1ZXIuY29tPokCVAQT
AQgAPhYhBDu1pmhkGCdcwlmMzYTxQCuHO2soBQJgIkfOAhsDBQkB1Q5eBQsJCAcC
BhUKCQgLAgQWAgMBAh4BAheAAAoJEITxQCuHO2soFXQP/3JW2r1utBNBy0Wx2OU/
ceiLbhjxZQ4m4sJ47yZTm6MCPttIhtV6RX1pK3Fz3bqldw6FeCGCPZvlrqzzTwES
87GtEjAgFZWMydXICM2N0gS/wAEccky2rOXC/s0yx1rtGcJAE/U3VxOvyM4Gz/q1
64qVti/OqUIJ7OsFK1iBseLUEDdfrsVQ6hMw/uOLZfBuAfj4o4McvawoOJW2MHfO
3gs4bkJk2UHinNC2iwbT44m/rlAqbO4ghiaGRhE3UJIjofxk5ZXd8emQM2k271ya
Du9vXGisaydG/cMo6jYD4xH18w2jw5eN/UJAX/DBLpYKGYQ9v9wRAVttOKptXARN
xioTI1lT5LFPHGW/JRsbnctGzangHhYwEwpnadjnTMW/mt/kdjI7k7aSYsWi2kyx
FHw3P/4KxAEp4G43xFP9TSUj4shw4Fa3YbKGry0PZ3KHlspd23q1V5FOw2EVCFMe
Snblu9LBYWBroG4HglplxkT/qggNyjhmnLwrS8gcHAUVroAw38YOuknRYIS9nItZ
2du9QZkBZpZoBc6pglAzXCknu4+HKKIw5pqCkKTgCLePBBpGd3gMfFigIf4azKuf
v9srVRXU5I2GbeOfEy9SbhEyeo1M6Gpu8iIxoAcV6VbCcHSD1lTegd8UApiDXBXw
cBMy+Z6FYYGBIbp9v6h0NJ+VtCJGaW5uIFNhdWVyIDxwcml2YXRlQGZpbm5zYXVl
ci5jb20+iQJUBBMBCAA+FiEEO7WmaGQYJ1zCWYzNhPFAK4c7aygFAmAiR+ACGwMF
CQHVDl4FCwkIBwIGFQoJCAsCBBYCAwECHgECF4AACgkQhPFAK4c7aygKSA//Z1r9
V9amxGJbTNK59A4Ws31YF/IxxzBdqccmmTa546wMSJuiJadm+E/TEgKtTyY1TlIr
QypbCNy8iA1BpGru2x2klSKjb5gm1faMvN13LWjyrKkonYa6fMxTDvYqYXA6x8hO
VKMkaoreWbJSMidgIGHbYgcvV5lswWgeFzK3kGnns7zfUSwPpugjklZpABNxCpfB
Wl699GnnyxW4WyaiZWUDojvvHqiz6rS3+PXgst0zIdkkXjZ6mBgntfKhClyAp+qJ
PKI/5r1dh0kcZUbpAQu6ju0wMTCpSa33FbNQsVbAsLOhGujCpA6bsIpk/V05kVQL
3AR66yNC2iT1CBVjwKTITLKK/gQ1bdUqRdvLHHsDb//ZrhTeo2NzwvueqdMqt3dq
cCuLJ1pEmnEg8rS2FKEhXT1O150NZDOoZCPb7ukWNwNKUqA+y4ntxV0vP7o7Fxab
ROo+ltn582zWAJpgqSc4zpRsCUjT53HVrLMe/xMt75hE0BpvhlL+GXwVnLznpQZx
ShIJggspv4SLokj9kThkFV/w6WEC70TkxX5rsACa6vVTb86HnZM97HRb5AdE0b48
3nKCP5PPp3g4/U+1SUPA2grX/5Xq1hslCZwsWrDtE7GAXdig6sWWjVmBEppxTG1r
qdeWYJKGOW3RFZtXVg4orbBgS8cnpz86K26ClC65Ag0EXzFTLgEQAJdV8anmgnjd
nLp3LDuII7Qi0mdpvnwwYDSLI9wTJAuHz8hp5Lqe+AGAkvPF8JsjQdia5n2iv9qi
C3LKT0PEf1lYWN9IlT0vlkPgeZ4AgXPxhuxLgJfYsSkb5V5r9734JHLA28mZeyFB
TXdn69lmafbxbGpE9baZ5e2B0dsIIllzLsh2GTD8M9r5rJ7Grvntoaad2mdHh7DJ
qPv6Fx/aif5IIh00fhF7xwNwK7uKyaH9vIGjzvM5wtskD4YEjHdOaNqRBN4v+0V5
Aoh7gHSoOvjr4dRx27EFZCCc+nh5+5AguRqi6k3Xd5tFJMoRMiadoF6SjTaKRsIM
L6ngPKwCT0gZgWXJXyuKQv/OfQHOCndF9Eah9JR4FMtrximzYzhBZYUZeiLKHhs0
ui/WdMxkNhfG31tAifmHII9HWzPBPidEjgAnPc/Dn0L12zbLe+bWlucbqgNCnkGF
QwyQgyQ68oNJ8ZVzDe2lIuKGnuq0E8w3CIPTg9qmXzC6PzOdnDqlDYgSgu2rodfL
Fq2n4uqYUply6O7gauBY1PUZZ+mLKuBeuq6qi/BZJyZObBvkfXNqQEGTUjGvaGZ2
bYP4k92Ko2vxoW10yYRKPMNwE4x0fW/P3R9DdCmn7MlHVKErgTIC3uFLzmDa3OI9
zXTedHjHI4x41gtyU7JWRpDqaEx0/tURABEBAAGJAjYEGAEIACAWIQQ7taZoZBgn
XMJZjM2E8UArhztrKAUCXzFTLgIbDAAKCRCE8UArhztrKJNyD/4ieTHHpigmo+zh
0B24p2UcyS+PwSVNn1R1zpWXons/FQP5t7QGmUrASXSeUbS9o59BIMZ22Q8y9Zxa
nQyki6o7IjO7Pdd/2gUI3v0D0guBJvpacFxgFRoJsfzGl/RSI0/RsYx7h02NMGTL
GlxYWnYIwFLEnlVZ1+8IehLMyFBIxaTPyeV+i+qrntnwUtwxqfjdydMD50bgbxkk
qLBk9Fun0Yfubmhz5CmGPi+0TFI3JAATOBQwFiILSqMCvViC5c/S6CTpt3hC6eqG
SsncBNTYRkx7LgdzhukFr2ZskhytXVVxnsjFSMknRX9Db29g5YrxNHtZwnQzHZir
uFJPODtrfY1jeqtgaeFFXdYijt/hg6Nv/QyAcRaKqM4abpV5LiCMDXVnOLT1uZoH
bA9tHgGbKZGPLkyGj/S4a8xe5u8VLE5sl6f4WYsNR4DXdg7ur+zGPhZ2xECg0Srz
ENn3k426YwioW8g2G6K6qi8z4yp6mbN5mg/9vN8OUum2j5hNZot4HWAg20xJSqVX
AfIJdrYqveuaiT/XFQx0wkYRcByP4cyb6PrRq69fnBRAWDSMYzmsY8mzpe2gYDBz
1Qmf/U+zrUpUSLUaRXD2JphHFmPWaJwc3HhJg8jQjZhbCSvqpDFLAd/3fVO100bj
0Sbbme0VyvRu9fw+y0xyohoKZNd6oQ==
=QLQV
-----END PGP PUBLIC KEY BLOCK-----
#+end_src

* Dotemacs
:PROPERTIES:
:CUSTOM_ID: h:30d120cd-d658-4520-a9b4-d78bd0b984bd
:EXPORT_HUGO_SECTION: /dotemacs
:EXPORT_FILE_NAME: _index
:END:

{{< partial "dotemacs-git-last-log" >}}

* Blog
:PROPERTIES:
:CUSTOM_ID: h:c761582c-bf98-473f-92fd-dca9374c819e
:EXPORT_HUGO_SECTION: /blog
:EXPORT_FILE_NAME: _index
:END:

This blog will mostly be about technology and close related topics.  In
the future I might split it into multiple blogs with different topics--
a hierarchically based system-- or a tag based system.

Right now there is a beta version of tags.  That can be found [[https://finnsauer.com/tags/][here]].

* Feeds
:PROPERTIES:
:CUSTOM_ID: h:62b9de36-a1c0-4b94-b25f-5401d710430e
:EXPORT_HUGO_SECTION: /
:EXPORT_FILE_NAME: feeds
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :weight 104
:END:

# TODO: remove the parentheses and add it as a foot note; still need to
# figure things more out

The specific RSS Feed of a tag can be found on their respective sites;
go to [[https://finnsauer.com/tags/][this page]] and select the one you want to subscribe (This is not a
typical subscription as you know it; you simply put the RSS Feed URL
into your RSS Feed reader and be done with it.  If you want to
unsubscribe, remove it.).  A master feed-- that is a feed that embodies
all the tags-- can be found [[https://finnsauer.com/blog/index.xml][here]].

* License
:PROPERTIES:
:CUSTOM_ID: h:5ac6a93c-858b-46c8-b4d8-963973a4d188
:EXPORT_HUGO_SECTION: /
:EXPORT_FILE_NAME: license
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :weight 105
:END:

TODO: more things on copyleft licenses and why you should use them.

+ GNU Public License Version 3.0 or later quick guide:
  + https://www.gnu.org/licenses/quick-guide-gplv3.html
+ Creative Commons BY-SA 4.0 quick guide:
  + https://creativecommons.org/licenses/by-sa/4.0/

* NO-HUGO Dummy Sites
:PROPERTIES:
:CUSTOM_ID: h:6edbcbb3-429f-4db5-8f98-ffae3e5600e9
:END:

** Blog
:PROPERTIES:
:CUSTOM_ID: h:615e67e6-1f88-4dd3-8f9e-74588059d3bd
:EXPORT_HUGO_SECTION: /
:EXPORT_FILE_NAME: dummy-blog
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :url blog/ :weight 103
:END:

** Dotemacs
:PROPERTIES:
:CUSTOM_ID: h:fa744b47-045f-4126-9647-3e6e3f079f1a
:EXPORT_HUGO_SECTION: /
:EXPORT_FILE_NAME: dummy-dotemacs
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :url dotemacs/ :weight 102
:END:

* NO-HUGO Blog Posts
:PROPERTIES:
:CUSTOM_ID: h:b3ace5f9-c588-481d-994d-3871b8bc6f45
:END:

** DONE Hello World                                              :org:emacs:
CLOSED: [2021-02-14 Sun]
:PROPERTIES:
:EXPORT_FILE_NAME: hello-world
:CUSTOM_ID: h:def96466-2080-40df-964e-7259f95e5575
:END:

#+begin_abstract
Some abstract text.  Optio cumque nihil impedit quo minus id quod maxime
placeat  facere  possimus  omnis  voluptas  assumenda  est  omnis  dolor
repellendus Temporibus autem quibusdam et aut officiis debitis aut rerum
necessitatibus  saepe  eveniet  ut  et voluptates  repudiandae  sint  et
molestiae  non recusandae  Itaque  earum rerum  hic  tenetur a  sapiente
delectus ut aut!
#+end_abstract

This is my first blog post; noch eine schöne Zeit!

#+begin_quote
This is a quote.

Over multiple lines!
#+end_quote
